package com.berrycrush.intellij.run

import com.intellij.openapi.project.Project
import java.io.File
import java.security.MessageDigest

/**
 * Generates temporary test wrapper classes for running specific scenario files.
 *
 * The BerryCrush JUnit test engine discovers scenarios from classpath patterns
 * defined in `@BerryCrushScenarios`. To run a specific file, we generate a
 * temporary test class that references only that file.
 *
 * ## Generated File Structure
 *
 * ```kotlin
 * package berrycrush.generated
 *
 * import org.berrycrush.junit.BerryCrushScenarios
 * import org.junit.platform.suite.api.IncludeEngines
 *
 * @IncludeEngines("berrycrush")
 * @BerryCrushScenarios(locations = ["/absolute/path/to/scenario.scenario"])
 * class BerryCrushWrapper_abc123
 * ```
 *
 * ## Generated File Location
 *
 * Files are generated in `{module}/build/generated-berrycrush-tests/`
 */
object TemporaryTestGenerator {

    private const val GENERATED_PACKAGE = "berrycrush.generated"
    private const val GENERATED_DIR = "build/generated-berrycrush-tests"

    /**
     * Generate a temporary test wrapper for the given scenario file.
     *
     * @param project The IntelliJ project
     * @param scenarioFilePath Absolute path to the scenario file
     * @param moduleDir Directory of the module containing the scenario
     * @return The generated test file, or null if generation failed
     */
    @Suppress("UnusedParameter") // project reserved for future use (e.g., project-specific settings)
    fun generateWrapper(
        project: Project,
        scenarioFilePath: String,
        moduleDir: File,
    ): GeneratedTestInfo? {
        val scenarioFile = File(scenarioFilePath)
        if (!scenarioFile.exists()) {
            return null
        }

        // Generate unique class name based on file path hash
        val hash = generateHash(scenarioFilePath)
        val className = "BerryCrushWrapper_$hash"

        // Create output directory
        val outputDir = File(moduleDir, "$GENERATED_DIR/${GENERATED_PACKAGE.replace('.', '/')}")
        outputDir.mkdirs()

        // Generate the test file
        val outputFile = File(outputDir, "$className.kt")
        val content = generateTestContent(className, scenarioFilePath)
        outputFile.writeText(content)

        return GeneratedTestInfo(
            testFile = outputFile,
            className = "$GENERATED_PACKAGE.$className",
            simpleClassName = className,
            generatedDir = File(moduleDir, GENERATED_DIR),
        )
    }

    /**
     * Generate a temporary test wrapper for a specific scenario within a file.
     *
     * @param project The IntelliJ project
     * @param scenarioFilePath Absolute path to the scenario file
     * @param scenarioName Name of the specific scenario to run
     * @param moduleDir Directory of the module containing the scenario
     * @return The generated test file, or null if generation failed
     */
    @Suppress("UnusedParameter") // scenarioName reserved for future tag-based filtering
    fun generateWrapperForScenario(
        project: Project,
        scenarioFilePath: String,
        scenarioName: String,
        moduleDir: File,
    ): GeneratedTestInfo? {
        val info = generateWrapper(project, scenarioFilePath, moduleDir) ?: return null

        // Note: Scenario-level filtering would require additional BerryCrush engine support
        // For now, we run the whole file. The engine would need to support tag filtering
        // like @BerryCrushTags(include = ["scenario:$scenarioName"])

        return info
    }

    /**
     * Clean up generated test files.
     *
     * @param info The generated test info to clean up
     */
    fun cleanup(info: GeneratedTestInfo) {
        // Delete the generated test file
        if (info.testFile.exists()) {
            info.testFile.delete()
        }

        // Try to clean up empty directories
        cleanEmptyDirectories(info.generatedDir)
    }

    /**
     * Clean up all generated test files in a module.
     *
     * @param moduleDir Directory of the module
     */
    fun cleanupAll(moduleDir: File) {
        val generatedDir = File(moduleDir, GENERATED_DIR)
        if (generatedDir.exists()) {
            generatedDir.deleteRecursively()
        }
    }

    private fun generateTestContent(className: String, scenarioFilePath: String): String {
        // Escape the path for use in a Kotlin string literal
        val escapedPath = scenarioFilePath.replace("\\", "\\\\")

        return """
            |package $GENERATED_PACKAGE
            |
            |import org.berrycrush.junit.BerryCrushScenarios
            |
            |/**
            | * Auto-generated test wrapper for running a specific scenario file.
            | * Generated by BerryCrush IntelliJ Plugin.
            | *
            | * This file can be safely deleted after test execution.
            | */
            |@BerryCrushScenarios(locations = ["file:$escapedPath"])
            |class $className
        """.trimMargin()
    }

    private fun generateHash(input: String): String {
        val md = MessageDigest.getInstance("MD5")
        val digest = md.digest(input.toByteArray())
        return digest.take(HASH_LENGTH).joinToString("") { "%02x".format(it) }
    }

    private fun cleanEmptyDirectories(dir: File) {
        if (!dir.exists() || !dir.isDirectory) return

        // Recursively clean subdirectories first
        dir.listFiles()?.filterNotNull()?.forEach { file ->
            if (file.isDirectory) {
                cleanEmptyDirectories(file)
            }
        }

        // Delete this directory if it's now empty
        if (dir.listFiles()?.isEmpty() == true) {
            dir.delete()
        }
    }

    private const val HASH_LENGTH = 8
}

/**
 * Information about a generated test wrapper.
 */
data class GeneratedTestInfo(
    /** The generated Kotlin test file */
    val testFile: File,
    /** Fully qualified class name (e.g., berrycrush.generated.BerryCrushWrapper_abc123) */
    val className: String,
    /** Simple class name (e.g., BerryCrushWrapper_abc123) */
    val simpleClassName: String,
    /** Root directory of generated files */
    val generatedDir: File,
)
